let shopItemsData = [
  {
    id: "mttc",
    name: "1899",
    price: 45,
    desc: "Multinational immigrants traveling from the old continent to the new..",
    img: "image/1899.jpg",
  },
  {
    id: "antm",
    name: "ANT MAN",
    price: 50,
    desc: "Scott Lang and Hope Van Dyne are dragged into the Quantum Realm, along..",
    img: "image/ant_man.jpg",
  },
  {
    id: "aqm",
    name: "AQUAMAN",
    price: 25,
    desc: "Arthur must enlist the help of his half-brother Orm in order to protect Atlantis..",
    img: "image/aquaman.jpg",
  },
  {
    id: "arrow",
    name: "ARROW",
    price: 55,
    desc: "Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his..",
    img: "image/arrow.jpg",
  },
  {
    id: "ba",
    name: "BLACK ADAM",
    price: 45,
    desc: "Nearly 5,000 years after he was bestowed with the Egyptian gods and..",
    img: "image/Black_Adam.jpg",
  },
  {
    id: "gjm",
    name: "GAJAMAN",
    price: 60,
    desc: "The Gajaman, gets a new job from the Magodisthuma, the local..",
    img: "image/gajaman.jpg",
  },
  {
    id: "got",
    name: "GAME OF THR..",
    price: 25,
    desc: "Nine noble families fight for control over the lands of Westeros, while an..",
    img: "image/game_of_thrones.jpg",
  },
  {
    id: "itct",
    name: "INTERCEPTOR",
    price: 50,
    desc: "One Army captain must use her years of tactical training and military expertise..",
    img: "image/Interceptor.jpg",
  },
  {
    id: "jw",
    name: "JOHN WICK",
    price: 40,
    desc: "John Wick uncovers a path to defeating The High Table. But before he can earn..",
    img: "image/john_wick.jpg",
  },
  {
    id: "plane",
    name: "PLANE",
    price: 25,
    desc: "A pilot finds himself caught in a war zone after he's forced to land his ..",
    img: "image/plane.jpg",
  },
  {
    id: "thor",
    name: "THOR",
    price: 30,
    desc: "Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to..",
    img: "image/Thor.jpg",
  },
  {
    id: "meg",
    name: "MEG",
    price: 30,
    desc: "A research team encounters multiple threats while exploring the depths of..",
    img: "image/meg.jpg",
  },
  {
    id: "wnd",
    name: "WEDNESDAY",
    price: 45,
    desc: "Follows Wednesday Addams' years as a student, when she attempts to..",
    img: "image/wednesday.jpg",
  },
  {
    id: "mh",
    name: "MONEY HEIST",
    price: 70,
    desc: "An unusual group of robbers attempt to carry out the most perfect..",
    img: "image/money_heist.jpg",
  },    
  {
    id: "scs",
    name: "SUCCESSION",
    price: 60,
    desc: "The Roy family is known for controlling the biggest media and entertainment..",
    img: "image/succession.jpg",
  },    
  {
    id: "ec",
    name: "ECHO",
    price: 80,
    desc: "Maya Lopez must face her past, reconnect with her Native American roots and..",
    img: "image/echo.webp",
  },    


];